version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      microsoft-dotnet:
        patterns:
          - dotnet-ef
          - Microsoft.AspNetCore.*
          - Microsoft.EntityFrameworkCore*
          - Microsoft.Extensions.*
        update-types:
          - minor
          - patch
      test-platform:
        patterns:
          - Microsoft.NET.Test.Sdk
          - xunit*
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
