<Project>

    <PropertyGroup>
        <VersionPrefix>0.14.0</VersionPrefix>
        <Authors>Skopka contributors</Authors>
        <Company>Skopka</Company>
        <Product>Skopka.Identity</Product>
        <Copyright>Copyright (c) Skopka contributors</Copyright>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/skopka/identity</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>identity;authentication;authorization;aspnetcore;security</PackageTags>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/skopka/identity.git</RepositoryUrl>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <Deterministic>true</Deterministic>
        <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md"
              Pack="true"
              PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)LICENSE"
              Pack="true"
              PackagePath="\" />
    </ItemGroup>

</Project>
