// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skopka.Identity.Ef.PostgreSql;

#nullable disable

namespace Skopka.Identity.Ef.Migrations
{
    [DbContext(typeof(PostgreSqlIdentityDbContext<PostgreSqlIdentityDesignTimeProfile>))]
    [Migration("20260803152624_AddLoginIdentifierRegistry")]
    partial class AddLoginIdentifierRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.AuthUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_at");

                    b.Property<DateTimeOffset?>("BlockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_until");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<int>("Flags")
                        .HasColumnType("integer")
                        .HasColumnName("flags");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedPhone")
                        .HasColumnType("text")
                        .HasColumnName("normalized_phone");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<bool>("PhoneConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_confirmed");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_users_normalized_email")
                        .HasFilter("deleted_at IS NULL AND normalized_email IS NOT NULL");

                    b.HasIndex("NormalizedPhone")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_users_normalized_phone")
                        .HasFilter("deleted_at IS NULL AND normalized_phone IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_users_normalized_user_name")
                        .HasFilter("deleted_at IS NULL AND normalized_user_name IS NOT NULL");

                    b.ToTable("auth_users", (string)null);
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.LoginIdentifierEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("NormalizedKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("normalized_key");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("UserId", "NormalizedKey")
                        .HasName("pk_identity_login_identifiers");

                    b.HasIndex("NormalizedKey")
                        .IsUnique()
                        .HasDatabaseName("ux_identity_login_identifiers_active_normalized_key")
                        .HasFilter("is_active = TRUE");

                    b.ToTable("identity_login_identifiers", (string)null);
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.RateLimitBucketEntity", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope");

                    b.Property<string>("PartitionVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("partition_version");

                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<int>("HitCount")
                        .HasColumnType("integer")
                        .HasColumnName("hit_count");

                    b.Property<DateTimeOffset>("LastHitAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_hit_at");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset>("WindowStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_started_at");

                    b.HasKey("Scope", "PartitionVersion", "KeyHash");

                    b.ToTable("identity_rate_limit_buckets", (string)null);
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.RefreshSessionEntity", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<string>("ClientName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_name");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TokenId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_identity_refresh_sessions_expires_at");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_identity_refresh_sessions_session_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_identity_refresh_sessions_user_id");

                    b.ToTable("identity_refresh_sessions", (string)null);
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_identity_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_identity_roles_normalized_name");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_identity_roles_parent_id");

                    b.ToTable("identity_roles", (string)null);
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserCredentialEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("PasswordVerifier")
                        .HasColumnType("text")
                        .HasColumnName("password_verifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserExternalLoginEntity", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Provider", "Subject")
                        .HasName("pk_user_external_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_external_logins_user_id");

                    b.ToTable("user_external_logins", (string)null);
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserProfileEntityBase", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_identity_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_identity_user_roles_role_id");

                    b.ToTable("identity_user_roles", (string)null);
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.VerificationChallengeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Binding")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("binding");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempt_count");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<DateTimeOffset?>("ProofExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proof_expires_at");

                    b.Property<string>("ProofHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("proof_hash");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("purpose");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<string>("Verifier")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("verifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "State")
                        .HasDatabaseName("ix_verification_challenges_user_state");

                    b.ToTable("verification_challenges", (string)null);
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserProfileEntity<Skopka.Identity.Ef.PostgreSql.PostgreSqlIdentityDesignTimeProfile>", b =>
                {
                    b.HasBaseType("Skopka.Identity.Ef.Entities.UserProfileEntityBase");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("profile");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.LoginIdentifierEntity", b =>
                {
                    b.HasOne("Skopka.Identity.Ef.Entities.AuthUserEntity", "User")
                        .WithMany("LoginIdentifiers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_login_identifiers_auth_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.RefreshSessionEntity", b =>
                {
                    b.HasOne("Skopka.Identity.Ef.Entities.AuthUserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.RoleEntity", b =>
                {
                    b.HasOne("Skopka.Identity.Ef.Entities.RoleEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_identity_roles_identity_roles_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserCredentialEntity", b =>
                {
                    b.HasOne("Skopka.Identity.Ef.Entities.AuthUserEntity", "User")
                        .WithOne("Credential")
                        .HasForeignKey("Skopka.Identity.Ef.Entities.UserCredentialEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserExternalLoginEntity", b =>
                {
                    b.HasOne("Skopka.Identity.Ef.Entities.AuthUserEntity", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_external_logins_auth_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserProfileEntityBase", b =>
                {
                    b.HasOne("Skopka.Identity.Ef.Entities.AuthUserEntity", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Skopka.Identity.Ef.Entities.UserProfileEntityBase", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("Skopka.Identity.Ef.Entities.RoleEntity", "Role")
                        .WithMany("Memberships")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_user_roles_identity_roles_role_id");

                    b.HasOne("Skopka.Identity.Ef.Entities.AuthUserEntity", "User")
                        .WithMany("RoleMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_user_roles_auth_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.VerificationChallengeEntity", b =>
                {
                    b.HasOne("Skopka.Identity.Ef.Entities.AuthUserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.AuthUserEntity", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("ExternalLogins");

                    b.Navigation("LoginIdentifiers");

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("RoleMemberships");
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.RoleEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
