// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skopka.Identity.Ef.PostgreSql;

#nullable disable

namespace Skopka.Identity.Ef.Migrations
{
    [DbContext(typeof(PostgreSqlIdentityDbContext<PostgreSqlIdentityDesignTimeProfile>))]
    partial class PostgreSqlIdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.AuthUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_at");

                    b.Property<DateTimeOffset?>("BlockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_until");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<int>("Flags")
                        .HasColumnType("integer")
                        .HasColumnName("flags");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedPhone")
                        .HasColumnType("text")
                        .HasColumnName("normalized_phone");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<bool>("PhoneConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_confirmed");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_users_normalized_email")
                        .HasFilter("deleted_at IS NULL AND normalized_email IS NOT NULL");

                    b.HasIndex("NormalizedPhone")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_users_normalized_phone")
                        .HasFilter("deleted_at IS NULL AND normalized_phone IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_users_normalized_user_name")
                        .HasFilter("deleted_at IS NULL AND normalized_user_name IS NOT NULL");

                    b.ToTable("auth_users", (string)null);
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserCredentialEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("PasswordVerifier")
                        .HasColumnType("text")
                        .HasColumnName("password_verifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserExternalLoginEntity", b =>
                {
                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Provider", "Subject");

                    b.HasIndex("UserId");

                    b.ToTable("user_external_logins", (string)null);
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserProfileEntityBase", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserProfileEntity<Skopka.Identity.Ef.PostgreSql.PostgreSqlIdentityDesignTimeProfile>", b =>
                {
                    b.HasBaseType("Skopka.Identity.Ef.Entities.UserProfileEntityBase");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("profile");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserCredentialEntity", b =>
                {
                    b.HasOne("Skopka.Identity.Ef.Entities.AuthUserEntity", "User")
                        .WithOne("Credential")
                        .HasForeignKey("Skopka.Identity.Ef.Entities.UserCredentialEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserExternalLoginEntity", b =>
                {
                    b.HasOne("Skopka.Identity.Ef.Entities.AuthUserEntity", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.UserProfileEntityBase", b =>
                {
                    b.HasOne("Skopka.Identity.Ef.Entities.AuthUserEntity", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Skopka.Identity.Ef.Entities.UserProfileEntityBase", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skopka.Identity.Ef.Entities.AuthUserEntity", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("ExternalLogins");

                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
