<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Skopka.Identity</RootNamespace>
        <Description>Public contracts, user models, commands and extension points for Skopka.Identity.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Skopka.Abstraction.OperationResult" Version="0.1.0" />
    </ItemGroup>

</Project>
