<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Skopka.Identity.Ef</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Skopka.Identity.Ef\Skopka.Identity.Ef.csproj" />
        <ProjectReference Include="..\Skopka.Identity\Skopka.Identity.csproj" />
    </ItemGroup>

</Project>
